export const USER_LOGIN_AUTHORIZATION_SUCCESS = 'USER_LOGIN_AUTHORIZATION_SUCCESS';
export const USER_LOGGEDOUT = 'USER_LOGGEDOUT';
export const MOVE_TO_PROFILE_SCREEN_SUCCESS = 'MOVE_TO_PROFILE_SCREEN_SUCCESS';
export const MOVE_TO_HOME_SCREEN = 'MOVE_TO_HOME_SCREEN';
export const MOVE_TO_GIST_SCREEN = 'MOVE_TO_GIST_SCREEN';
export const FETCH_USER_GIST = 'FETCH_USER_GIST';
export const FETCH_USER_GIST_SUCCESS = 'FETCH_USER_GIST_SUCCESS';

export const FETCH_PUBLIC_GISTS_SUCCESS = 'FETCH_PUBLIC_GISTS_SUCCESS';
export const SET_IS_USER_GIST = 'SET_IS_USER_GIST';
export const SET_LOADING = 'SET_LOADING';
export const FETCH_GRID_DATA = 'FETCH_GRID_DATA';
export const SEARCH_GIST = 'SEARCH_GIST';
export const SET_VISITED_PAGE = 'SET_VISITED_PAGE'



